"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


from django.contrib import messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%rlj+=^p&p+w62&*mr)3@=!w%3g-6pxyt7oz!=zs37mr3v^&qp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ['172.16.33.98','rapidsrv.duckdns.org']

ALLOWED_HOSTS = ['172.16.33.98','127.0.0.1','localhost']  # <-- Updated!
# ALLOWED_HOSTS = ['172.16.33.97','esd.hexflow.au','localhost']  # <-- Updated!


CSRF_TRUSTED_ORIGINS = ['https://esd.hexflow.au']  # <-- Updated!

PAYPAL_SECRET='EMnAWe06ioGtouJs7gLYT9chK9-2jJ--7MKRXpI8FesmY_2Kp-d_7aCqff7M9moEJBvuXoBO4clKtY0v'
# Application definition
 
   
# Application definition 

INSTALLED_APPS = [
   'jazzmin',
    'clearcache',
    
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "allauth",
    "allauth.account",
    'landing',
    'authorisation',
    'dashboard',
    
    'crispy_forms',
    'crispy_bootstrap5',
     'corsheaders',
   
]
 


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'




DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'hexflows',
'USER': 'root',
'PASSWORD': '',
'HOST': '',
'PORT': '',
'OPTIONS': {
'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}

}
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'

OPENAI_API_KEYS = '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'

SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'

# CONTENT_API_KEYS = 'beed94d14e0e32676281afe883'
# BLOG_URL = 'https://test.hexflow.au/ghost/'

DJANGORESIZED_DEFAULT_SIZE = [500, 500]
DJANGORESIZED_DEFAULT_QUALITY = 75
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'PNG': ".png"}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap', 'uni_form', 'bootstrap3','bootstrap5', 'bootstrap4', 'semantic-ui')

# CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'uni_form'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# EMAIL_BACK


EMAIL_HOST = 'mail.hexflow.com.au'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'easir.m@hexflow.com.au'
EMAIL_HOST_PASSWORD = 'LgYZ?xU396U['
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'TestSite Team <noreply@example.com>'


JAZZMIN_SETTINGS = {

    
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "AI",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "AI",
     "site_brand": "AI",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "landing/img/esd.ai-2.jpg",
     "login_logo": "admin/img/esd.ai-2.jpg",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": True,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    
     # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["auth.User", "auth.Group","dashboard.profile"],

    
    
      # Welcome text on the login screen
    "welcome_sign": "Welcome to the esdAI",
       # Copyright on the footer
    "copyright": "esd AI",
    "version": "esd AI",

    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        # {"name": "Pricing ", "url": "http://127.0.0.1:8000/about", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        
    ],
    
 "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "dashboard.Blogsection": "	fas fa-light fa-list",
        "dashboard.Blog": "fas fa-pen-nib",
        "dashboard.Membership": "fas fa-light-fa-gear",
        "dashboard.profile": "	fas fa-user-tie",


        
    },   
     
}

JAZZMIN_UI_TWEAKS = {
   
    "theme": "flatly",
    
}