# Generated by Django 4.1.2 on 2023-03-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('webIdea', models.CharField(blank=True, max_length=200, null=True)),
                ('assistant', models.CharField(blank=True, max_length=100, null=True)),
                ('wordCount', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WebSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('wordCount', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.web')),
            ],
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
