# Generated by Django 4.1.2 on 2023-03-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_web_websection_delete_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='webIdea',
        ),
    ]
