# Generated by Django 4.1.2 on 2023-03-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_web_webidea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='assistant',
            new_name='web',
        ),
    ]
