# Generated by Django 4.1.7 on 2023-04-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1Title', models.CharField(blank=True, max_length=100, null=True)),
                ('section1Description', models.TextField(blank=True, null=True)),
                ('callToAction', models.CharField(blank=True, max_length=50, null=True)),
                ('section1Image', models.ImageField(default='default.jpg', upload_to='landing_page_images')),
                ('section3Title', models.CharField(blank=True, max_length=100, null=True)),
                ('section3Description', models.TextField(blank=True, null=True)),
                ('section3Image', models.ImageField(default='default.jpg', upload_to='landing_page_images')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LpgService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1Title', models.CharField(blank=True, max_length=200, null=True)),
                ('section1Description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('lpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lpg')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LpgFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1Title', models.CharField(blank=True, max_length=200, null=True)),
                ('section1Description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('lpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lpg')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
    ]
