# Generated by Django 4.1.7 on 2023-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_lpg_lpgservice_lpgfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpgfeatures',
            old_name='section1Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lpgfeatures',
            old_name='section1Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lpgservice',
            old_name='section1Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lpgservice',
            old_name='section1Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='lpgfeatures',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='landing_page_images'),
        ),
    ]
