# Generated by Django 4.2.3 on 2023-07-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_content_contentsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsection',
            name='content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ContentSection',
        ),
    ]
