# Generated by Django 4.2.3 on 2023-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_content_contentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_topic', models.CharField(max_length=60)),
                ('note_type', models.CharField(max_length=20)),
                ('note_length', models.IntegerField()),
                ('language_style', models.CharField(max_length=20)),
                ('key_concepts', models.TextField()),
                ('additional_instructions', models.TextField()),
                ('study_level', models.CharField(max_length=20)),
                ('citation_format', models.CharField(max_length=20)),
                ('include_examples', models.CharField(max_length=5)),
                ('visual_aids', models.CharField(max_length=5)),
                ('text_formatting', models.CharField(max_length=10)),
                ('content_organization', models.TextField()),
                ('generated_note', models.TextField()),
            ],
        ),
    ]
