# Generated by Django 4.2.3 on 2023-08-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
