# Generated by Django 4.2.3 on 2023-08-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='ai_response',
            new_name='chatgpt_response',
        ),
    ]
