# Generated by Django 4.2.3 on 2023-08-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_ai_response_conversation_chatgpt_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='chatgpt_response',
            new_name='ai_response',
        ),
    ]
