# Generated by Django 4.2.3 on 2023-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_chatmessages_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=255),
        ),
    ]
