# Generated by Django 4.2.3 on 2023-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('generated_recipe', models.TextField()),
                ('cuisine', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
