# Generated by Django 4.2.3 on 2023-08-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_recipecreator_delete_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecreator',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipecreator',
            name='dietary_preference',
        ),
        migrations.RemoveField(
            model_name='recipecreator',
            name='generated_recipe',
        ),
        migrations.RemoveField(
            model_name='recipecreator',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipecreator',
            name='user_input',
        ),
    ]
