# Generated by Django 4.2.3 on 2023-08-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_recipecreator_cuisine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCreator',
            new_name='RecipeC',
        ),
    ]
