# Generated by Django 4.2.3 on 2023-08-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_recipe_delete_recipec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_preference',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
    ]
