# Generated by Django 4.2.3 on 2023-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_recipe_cuisine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('generated_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
