# Generated by Django 4.2.3 on 2023-09-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
