# Generated by Django 4.2.10 on 2025-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_delete_userinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('price_agoda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_booking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('star_rating', models.FloatField()),
                ('agoda_url', models.URLField(blank=True, null=True)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='chatmessages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='content',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='contentsection',
            name='content',
        ),
        migrations.DeleteModel(
            name='GeneratedProductName',
        ),
        migrations.DeleteModel(
            name='GeneratedRecipe',
        ),
        migrations.RemoveField(
            model_name='lpg',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='lpgfeatures',
            name='lpg',
        ),
        migrations.RemoveField(
            model_name='lpgfeatures',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='lpgservice',
            name='lpg',
        ),
        migrations.RemoveField(
            model_name='lpgservice',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='openaimessages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payhistory',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='payhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudyNote',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='web',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='websection',
            name='web',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogSection',
        ),
        migrations.DeleteModel(
            name='ChatMessages',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ContentSection',
        ),
        migrations.DeleteModel(
            name='Lpg',
        ),
        migrations.DeleteModel(
            name='LpgFeatures',
        ),
        migrations.DeleteModel(
            name='LpgService',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='OpenaiMessages',
        ),
        migrations.DeleteModel(
            name='PayHistory',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
        migrations.DeleteModel(
            name='WebSection',
        ),
    ]
